name: "Unit test"
on:
  push:
    branches:
    - master

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4.5.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: "3.10"
    - name: Install Dependencies
      run: |
        pip install .
        pip install .[test]
    - name: unit test
      run: |
        pytest tests/unit
